/**
 * utils/install_script.js — 一键安装脚本纯函数生成器
 *
 * 职责：
 *   - 由 install_packages 行参数（slug / 目标机服务器地址 / 安装目录 / 是否内嵌
 *     local_config）生成可在 Windows PowerShell 5.1 直接执行的安装脚本文本；
 *   - 生成两条执行命令：直连长命令与 Sink 短链短命令；
 *   - 对所有会嵌入脚本字符串的字段做白名单校验（禁止引号 / 控制字符），
 *     保证脚本不可被注入改写。
 *
 * 关键不变量：
 *   - 生成脚本内容为纯 ASCII（CRLF 换行），规避 PowerShell 5.1 对响应
 *     字符集的处理差异（irm | iex 管道下中文注释可能被误解码）；
 *   - 单引号字符串中的单引号一律双写转义；local_config.json 的值经
 *     JSON.stringify 嵌入，保证 JSON 合法；
 *   - 本模块不依赖数据库与网络，可被 smoke_test 直接测试。
 */

/** 安装入口 slug 白名单（与 schema.sql CHAR(16) 对应，实际生成长度 16） */
const SLUG_RE = /^[A-Za-z0-9]{8,64}$/;

/** Sink 自定义短链 slug 白名单（宽松：字母数字与连字符，Sink 端会再校验一次） */
const SINK_SLUG_RE = /^[A-Za-z0-9][A-Za-z0-9-]{0,63}$/;

/**
 * 校验并归一化目标机可达的服务器地址（写入脚本与 local_config.json）。
 * 要求 http(s):// 开头、无空白与引号；去除末尾多余的 /。
 * @param {string} input
 * @returns {string} 归一化后的地址
 * @throws {Error} 非法时抛出中文错误
 */
function normalizeClientBaseUrl(input) {
  let url = String(input || '').trim();
  if (!/^https?:\/\/[^\s'"]{1,240}$/.test(url)) {
    throw new Error('客户端服务器地址非法：需以 http:// 或 https:// 开头，且不含空白与引号');
  }
  url = url.replace(/\/+$/, '');
  return url;
}

/**
 * 校验并归一化目标机安装目录（Windows 绝对路径，如 C:\HomeworkTime）。
 * 禁止引号与控制字符；去除末尾的 \。
 * @param {string} input
 * @returns {string} 归一化后的目录
 * @throws {Error} 非法时抛出中文错误
 */
function normalizeInstallDir(input) {
  let dir = String(input || '').trim();
  if (!/^[A-Za-z]:\\[^'"\x00-\x1f]{1,240}$/.test(dir)) {
    throw new Error('安装目录非法：需为 Windows 绝对路径（如 C:\\HomeworkTime），且不含引号');
  }
  if (/\\$/.test(dir) || /\s$/.test(dir)) {
    throw new Error('安装目录不能以反斜杠或空格结尾');
  }
  return dir;
}

/**
 * 校验安装入口 slug。
 * @param {string} slug
 * @returns {boolean}
 */
function isValidSlug(slug) {
  return SLUG_RE.test(String(slug || ''));
}

/**
 * 校验 Sink 自定义短链 slug（可空；空表示由 Sink 自动生成）。
 * @param {string} slug
 * @returns {boolean}
 */
function isValidSinkSlug(slug) {
  const s = String(slug || '').trim();
  return s === '' || SINK_SLUG_RE.test(s);
}

/**
 * 解析 Sink 短链服务地址 → { origin, hostname }。
 * hostname（不含端口）即 Sink 创建短链所需的 domain 字段。
 * @param {string} input 形如 https://s.example.com 的 Sink 服务地址
 * @returns {{origin: string, hostname: string}}
 * @throws {Error} 非法时抛出中文错误
 */
function parseSinkUrl(input) {
  let url;
  try {
    url = new URL(String(input || '').trim());
  } catch (e) {
    throw new Error('短链服务地址非法：需为完整的 http(s) URL');
  }
  if (url.protocol !== 'http:' && url.protocol !== 'https:') {
    throw new Error('短链服务地址非法：需以 http:// 或 https:// 开头');
  }
  return { origin: url.origin, hostname: url.hostname };
}

/** PowerShell 单引号字符串转义：单引号双写 */
function psSingleQuoted(value) {
  return String(value).replace(/'/g, "''");
}

/**
 * 拼接脚本下载 URL（长命令与 Sink 短链的跳转目标）。
 * @param {string} clientBaseUrl 已归一化的目标机可达服务器地址
 * @param {string} slug 安装入口 slug
 * @returns {string}
 */
function buildScriptUrl(clientBaseUrl, slug) {
  return `${clientBaseUrl}/api/install/s/${slug}`;
}

/**
 * 生成目标机执行的 PowerShell 一键安装命令（直连版）。
 * @param {string} scriptUrl 脚本下载 URL
 * @returns {string}
 */
function buildInstallCommand(scriptUrl) {
  return `powershell -NoProfile -ExecutionPolicy Bypass -Command "irm '${psSingleQuoted(scriptUrl)}' | iex"`;
}

/**
 * 生成 Sink 短链版安装命令（更短，便于口头转达 / 手工敲入）。
 * @param {string} shortUrl Sink 返回的短链 URL
 * @returns {string}
 */
function buildShortCommand(shortUrl) {
  return buildInstallCommand(shortUrl);
}

/**
 * 生成一键安装 PowerShell 脚本文本。
 *
 * 脚本行为（Windows PowerShell 5.1 兼容）：
 *   1) 结束正在运行的 HomeworkTime 进程（支持重复执行覆盖安装）；
 *   2) 下载安装包 zip 到临时目录；
 *   3) 解压到安装目录（允许 zip 根级直接含 HomeworkTime.exe，
 *      或含一层同名文件夹）；
 *   4) embedConfig 时在 exe 同级写入 local_config.json
 *      （server_base_url + 当前 client_token + autostart，免首次运行引导；
 *      注册表自启动由客户端启动时按 local_config.autostart 自行写入）；
 *   5) 启动 HomeworkTime.exe。
 *
 * @param {object} opts
 * @param {string} opts.slug            安装入口 slug
 * @param {string} opts.clientBaseUrl   目标机可达的服务器地址（已归一化）
 * @param {string} opts.installDir      目标机安装目录（已归一化）
 * @param {boolean} opts.embedConfig    是否写入 local_config.json
 * @param {string|null} opts.clientToken 当前客户端 Token（embedConfig 时嵌入；可为空串）
 * @returns {string} CRLF 换行的脚本文本（纯 ASCII）
 * @throws {Error} 参数未通过白名单校验时抛出
 */
function buildInstallScript(opts) {
  const { slug, clientBaseUrl, installDir, embedConfig, clientToken } = opts || {};
  if (!isValidSlug(slug)) throw new Error('安装 slug 非法');
  const base = normalizeClientBaseUrl(clientBaseUrl);
  const dir = normalizeInstallDir(installDir);
  const scriptUrl = buildScriptUrl(base, slug);

  const lines = [
    `# HomeworkTime one-click install script (generated by server, do not edit)`,
    `# Usage: ${buildInstallCommand(scriptUrl)}`,
    `$ErrorActionPreference = 'Stop'`,
    `$ProgressPreference = 'SilentlyContinue'`,
    `try { [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12 } catch { }`,
    ``,
    `$Base   = '${psSingleQuoted(base)}'   # server base url reachable from this machine`,
    `$Slug   = '${psSingleQuoted(slug)}'`,
    `$Dir    = '${psSingleQuoted(dir)}'   # install dir`,
    `$PkgUrl = "$Base/api/install/s/$Slug/package"`,
    ``,
    `Write-Host '[1/5] Stopping running HomeworkTime (if any)...'`,
    `Get-Process -Name 'HomeworkTime' -ErrorAction SilentlyContinue | Stop-Process -Force`,
    `Start-Sleep -Milliseconds 500`,
    ``,
    `Write-Host '[2/5] Downloading install package...'`,
    `$Zip = Join-Path $env:TEMP ('ht_install_' + [guid]::NewGuid().ToString('N') + '.zip')`,
    `Invoke-WebRequest -UseBasicParsing -Uri $PkgUrl -OutFile $Zip`,
    ``,
    `Write-Host ('[3/5] Extracting to ' + $Dir + ' ...')`,
    `New-Item -ItemType Directory -Force -Path $Dir | Out-Null`,
    `Expand-Archive -Path $Zip -DestinationPath $Dir -Force`,
    `Remove-Item -Path $Zip -Force`,
    ``,
    `Write-Host '[4/5] Locating application...'`,
    `$Exe = Join-Path $Dir 'HomeworkTime.exe'`,
    `if (-not (Test-Path -LiteralPath $Exe)) {`,
    `  $Hit = Get-ChildItem -Path $Dir -Recurse -Filter 'HomeworkTime.exe' -File | Select-Object -First 1`,
    `  if ($Hit) { $Exe = $Hit.FullName }`,
    `}`,
    `if (-not (Test-Path -LiteralPath $Exe)) {`,
    `  throw 'Install failed: HomeworkTime.exe not found after extraction.'`,
    `}`,
    `$AppDir = Split-Path -Parent $Exe`,
    ``
  ];

  if (embedConfig) {
    // local_config.json 的值经 JSON.stringify 嵌入，保证 JSON 合法；
    // 以 .NET WriteAllText 落盘（UTF-8 无 BOM，兼容客户端 json.load）。
    const configJson = JSON.stringify(
      {
        server_base_url: base,
        client_token: String(clientToken || ''),
        poll_interval_sec: 10,
        autostart: true
      },
      null,
      2
    );
    lines.push(
      `# Write local_config.json next to the exe (skips the first-run guide window).`,
      `$Config = @'`,
      configJson,
      `'@`,
      `[System.IO.File]::WriteAllText((Join-Path $AppDir 'local_config.json'), $Config)`,
      ``
    );
  } else {
    lines.push(
      `# local_config.json is NOT written (embed config disabled):`,
      `# the first-run guide window will ask for server address and token on launch.`,
      ``
    );
  }

  lines.push(
    `Write-Host '[5/5] Starting HomeworkTime...'`,
    `Start-Process -FilePath $Exe -WorkingDirectory $AppDir`,
    `Write-Host 'HomeworkTime installed successfully.'`
  );

  // PowerShell 依赖 CRLF：here-string 终止符 '@ 必须位于行首
  return lines.join('\r\n') + '\r\n';
}

module.exports = {
  SLUG_RE,
  SINK_SLUG_RE,
  normalizeClientBaseUrl,
  normalizeInstallDir,
  isValidSlug,
  isValidSinkSlug,
  parseSinkUrl,
  buildScriptUrl,
  buildInstallCommand,
  buildShortCommand,
  buildInstallScript
};
